# Step 3: Feature Selection

### Experiment 1: Use PCA 100 features

1. use selected feature, fit xgboost 

2. Optuna to tune

3. cross validation

4. final model; score test set

In [1]:
import os
import numpy as np
import pandas as pd

import optuna

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import f1_score, make_scorer, accuracy_score

import xgboost as xgb
from sklearn.multioutput import MultiOutputClassifier

/Applications/anaconda3/envs/wids-env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
current_dir = os.getcwd()
home_dir = os.path.abspath(os.path.join(current_dir, os.pardir))
data_dir = os.path.join(home_dir, 'data/')

In [3]:
train_cat = pd.read_csv(os.path.join(data_dir, 'intermediate/encoded_train_cat.csv'))
train_quant = pd.read_csv(os.path.join(data_dir, 'intermediate/train_quant_filled.csv'))
train_fcm_100 = pd.read_csv(os.path.join(data_dir, 'intermediate/train_pca_100.csv'))
train_fcm_500 = pd.read_csv(os.path.join(data_dir, 'intermediate/train_pca_500.csv'))

test_cat = pd.read_csv(os.path.join(data_dir, 'intermediate/encoded_test_cat.csv'))
test_quant = pd.read_csv(os.path.join(data_dir, 'intermediate/test_quant_filled.csv'))
test_fcm_100 = pd.read_csv(os.path.join(data_dir, 'intermediate/test_pca_100.csv'))
test_fcm_500 = pd.read_csv(os.path.join(data_dir, 'intermediate/test_pca_500.csv'))

# selected features
features_100 = pd.read_csv(os.path.join(data_dir, 'intermediate/common_features_selected.csv'), header=None)
features_500 = pd.read_csv(os.path.join(data_dir, 'intermediate/common_features_selected_500.csv'), header=None)

train_label = pd.read_excel(os.path.join(data_dir, 'TRAIN_NEW/TRAINING_SOLUTIONS.xlsx'))

In [4]:
# Join data
X = train_cat.merge(train_quant, on='participant_id', how='left').merge(train_fcm_100, on='participant_id', how='left')
# X = X.drop(columns=['participant_id'], axis=1)
y = train_label.copy()
# y = y.drop(columns=['participant_id'], axis=1)

In [5]:
features_100_list = features_100[0].tolist()
features_100_list = [x.removesuffix('_scaled') for x in features_100_list]

In [7]:
# only keep the selected features
X = X[features_100_list + ['participant_id']]

In [8]:
# merge test data
X_test = test_cat.merge(test_quant, on='participant_id', how='left').merge(test_fcm_100, on='participant_id', how='left')

test_participant_id = X_test['participant_id']

X_test['MRI_Track_Scan_Location_3.0'] = 0

X_test = X_test[features_100_list]

Try scaling the features

In [9]:
# 1. Select numeric columns to scale
numeric_features = X.select_dtypes(include=['float64', 'int64']).columns.tolist()

# 2. Initialize the scaler
scaler = StandardScaler()

# 3. Fit the scaler on training data only
scaler.fit(X[numeric_features])

# 4. Transform both train and val
X_scaled = X.copy()
X_test_scaled = X_test.copy()

X_scaled[numeric_features] = scaler.transform(X[numeric_features])
X_test_scaled[numeric_features] = scaler.transform(X_test[numeric_features])

In [10]:
# Split training and test data
X_train, X_val, y_train, y_val = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

In [11]:
X_train = X_train.drop(columns=['participant_id'], axis=1)
y_train = y_train.drop(columns=['participant_id'], axis=1)

In [12]:
# Custom scoring function for weighted F1 score
def weighted_f1(y_true, y_pred):
    # Ensure that y_true and y_pred are numpy arrays
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    
    f1_adhd = f1_score(y_true[:, 0], y_pred[:, 0])
    f1_sex = f1_score(y_true[:, 1], y_pred[:, 1])
    return (2/3) * f1_adhd + (1/3) * f1_sex

In [13]:
y_train

      ADHD_Outcome  Sex_F
215              1      0
482              1      0
27               1      1
1169             0      0
762              1      0
...            ...    ...
1044             0      1
1095             0      0
1130             0      1
860              0      0
1126             0      1

[849 rows x 2 columns]

In [16]:
# Objective function for Optuna optimization
def objective(trial):
    # Define the hyperparameters to tune
    params = {
        'objective': 'binary:logistic',
        'eval_metric': 'logloss',
        'max_depth': trial.suggest_int('max_depth', 3, 20),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'n_estimators': trial.suggest_int('n_estimators', 50, 500),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),
        'gamma': trial.suggest_float('gamma', 0, 10),
        'random_state': 42,
        'n_jobs': -1,
        'scale_pos_weight': 0.46
    }

    # Define the base model
    base_model = xgb.XGBClassifier(**params)

    # Wrap it with MultiOutputClassifier
    multi_model = MultiOutputClassifier(base_model)

    # Perform cross-validation (here we're using 5-fold cross-validation)
    scores = cross_val_score(multi_model, X_train, y_train, cv=5, scoring=make_scorer(weighted_f1))

    # Return the mean of the cross-validation scores
    return np.mean(scores)

In [17]:
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

print("Best params:", study.best_trial.params)

[I 2025-04-28 13:34:31,094] A new study created in memory with name: no-name-5c2622c8-15e3-488a-a8b0-c14c481c4c6d
[I 2025-04-28 13:34:34,715] Trial 0 finished with value: 0.5087921490124172 and parameters: {'max_depth': 3, 'learning_rate': 0.20485432961364955, 'n_estimators': 492, 'subsample': 0.7569136974224828, 'colsample_bytree': 0.945283541001511, 'gamma': 1.608258745746014}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:35,877] Trial 1 finished with value: 0.4660258907453982 and parameters: {'max_depth': 19, 'learning_rate': 0.1312583139660052, 'n_estimators': 58, 'subsample': 0.6948112771657976, 'colsample_bytree': 0.9616369516091042, 'gamma': 4.297508011113505}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:39,001] Trial 2 finished with value: 0.48361912916786576 and parameters: {'max_depth': 14, 'learning_rate': 0.1092093077010467, 'n_estimators': 445, 'subsample': 0.7706137136045297, 'colsample_bytree': 0.7806301510162493, 'gamma': 2.3746155143823753}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:41,713] Trial 3 finished with value: 0.35408705405469204 and parameters: {'max_depth': 8, 'learning_rate': 0.07435402933864174, 'n_estimators': 483, 'subsample': 0.945841622296219, 'colsample_bytree': 0.6731676233171267, 'gamma': 8.794101792401106}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:42,901] Trial 4 finished with value: 0.3778326171384402 and parameters: {'max_depth': 19, 'learning_rate': 0.08762392874227648, 'n_estimators': 133, 'subsample': 0.885677066950831, 'colsample_bytree': 0.8170547970545283, 'gamma': 9.140400497606121}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:46,939] Trial 5 finished with value: 0.48492844745472485 and parameters: {'max_depth': 5, 'learning_rate': 0.014282750581084965, 'n_estimators': 194, 'subsample': 0.9189635449451181, 'colsample_bytree': 0.7429169270481344, 'gamma': 1.0937042973940692}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:48,170] Trial 6 finished with value: 0.3914327449371484 and parameters: {'max_depth': 19, 'learning_rate': 0.17418049849610107, 'n_estimators': 171, 'subsample': 0.6369982562382498, 'colsample_bytree': 0.6395098607535222, 'gamma': 9.519220291518987}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:48,932] Trial 7 finished with value: 0.4142478314068729 and parameters: {'max_depth': 6, 'learning_rate': 0.17321135003017643, 'n_estimators': 52, 'subsample': 0.7100981946459426, 'colsample_bytree': 0.6715372949755004, 'gamma': 7.076356262089205}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:49,738] Trial 8 finished with value: 0.41715785778697284 and parameters: {'max_depth': 9, 'learning_rate': 0.22110307114920996, 'n_estimators': 57, 'subsample': 0.7888127992117354, 'colsample_bytree': 0.8855360767266907, 'gamma': 7.070364351197439}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:54,427] Trial 9 finished with value: 0.50563505226193 and parameters: {'max_depth': 6, 'learning_rate': 0.06231321773241319, 'n_estimators': 433, 'subsample': 0.739957476643023, 'colsample_bytree': 0.827597622119765, 'gamma': 0.8445250351470579}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:34:56,619] Trial 10 finished with value: 0.46598631305730187 and parameters: {'max_depth': 3, 'learning_rate': 0.2959081600845893, 'n_estimators': 315, 'subsample': 0.8613267804097232, 'colsample_bytree': 0.9824482944325077, 'gamma': 3.514740610587533}. Best is trial 0 with value: 0.5087921490124172.
[I 2025-04-28 13:35:00,379] Trial 11 finished with value: 0.5564602130144541 and parameters: {'max_depth': 12, 'learning_rate': 0.24210369559800723, 'n_estimators': 386, 'subsample': 0.7216284881410742, 'colsample_bytree': 0.8893099177254171, 'gamma': 0.19366193092875328}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:05,030] Trial 12 finished with value: 0.5520245454031962 and parameters: {'max_depth': 14, 'learning_rate': 0.24278501648397072, 'n_estimators': 359, 'subsample': 0.6121500447636383, 'colsample_bytree': 0.9053346267323624, 'gamma': 0.049778526645865906}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:09,398] Trial 13 finished with value: 0.5521417238750841 and parameters: {'max_depth': 14, 'learning_rate': 0.27138620412760617, 'n_estimators': 347, 'subsample': 0.6040015120434014, 'colsample_bytree': 0.8947996656965491, 'gamma': 0.045978760969026235}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:12,091] Trial 14 finished with value: 0.5130255291779553 and parameters: {'max_depth': 14, 'learning_rate': 0.27821703319803115, 'n_estimators': 372, 'subsample': 0.6599422050206375, 'colsample_bytree': 0.8755272332516517, 'gamma': 2.7828063506647975}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:14,154] Trial 15 finished with value: 0.44804637934636393 and parameters: {'max_depth': 11, 'learning_rate': 0.25510975603325947, 'n_estimators': 294, 'subsample': 0.82766487742716, 'colsample_bytree': 0.8507465965480548, 'gamma': 5.478910853510597}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:19,582] Trial 16 finished with value: 0.5306282837135171 and parameters: {'max_depth': 12, 'learning_rate': 0.20281297216897817, 'n_estimators': 384, 'subsample': 0.9984862133461876, 'colsample_bytree': 0.9245587367467513, 'gamma': 0.01027326507763876}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:21,904] Trial 17 finished with value: 0.5016974741622429 and parameters: {'max_depth': 17, 'learning_rate': 0.2673996761149077, 'n_estimators': 277, 'subsample': 0.6745653743605562, 'colsample_bytree': 0.7323085424768419, 'gamma': 2.112000125827447}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:23,775] Trial 18 finished with value: 0.4905010569657263 and parameters: {'max_depth': 16, 'learning_rate': 0.2996276769879847, 'n_estimators': 220, 'subsample': 0.6029355353967467, 'colsample_bytree': 0.9935948805666094, 'gamma': 5.377733727584108}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:26,228] Trial 19 finished with value: 0.4922957136475815 and parameters: {'max_depth': 11, 'learning_rate': 0.23208129557157597, 'n_estimators': 329, 'subsample': 0.7092492088000176, 'colsample_bytree': 0.7923186000838318, 'gamma': 3.4800198664173583}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:28,583] Trial 20 finished with value: 0.5124311901578051 and parameters: {'max_depth': 16, 'learning_rate': 0.18772467572952273, 'n_estimators': 242, 'subsample': 0.8202099795619019, 'colsample_bytree': 0.871488773163945, 'gamma': 1.2355269823463824}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:32,634] Trial 21 finished with value: 0.5421942100940026 and parameters: {'max_depth': 13, 'learning_rate': 0.24094357306319608, 'n_estimators': 358, 'subsample': 0.6068823155016827, 'colsample_bytree': 0.9000979946822809, 'gamma': 0.18875327725701274}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:37,266] Trial 22 finished with value: 0.5421948217522001 and parameters: {'max_depth': 15, 'learning_rate': 0.254512244303683, 'n_estimators': 419, 'subsample': 0.6393640370011445, 'colsample_bytree': 0.919366405960765, 'gamma': 0.030519486369272292}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:40,556] Trial 23 finished with value: 0.5271311246646924 and parameters: {'max_depth': 12, 'learning_rate': 0.2178473092437747, 'n_estimators': 404, 'subsample': 0.6267510510724793, 'colsample_bytree': 0.8533282383637383, 'gamma': 0.9018684485016888}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:43,489] Trial 24 finished with value: 0.5124169106906002 and parameters: {'max_depth': 10, 'learning_rate': 0.15249958446043435, 'n_estimators': 341, 'subsample': 0.6725694966784513, 'colsample_bytree': 0.9353092505805288, 'gamma': 1.8574203849650983}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:45,539] Trial 25 finished with value: 0.503391050638247 and parameters: {'max_depth': 17, 'learning_rate': 0.2801713256815304, 'n_estimators': 255, 'subsample': 0.7365198222694935, 'colsample_bytree': 0.9009117634287738, 'gamma': 3.076069975407343}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:49,158] Trial 26 finished with value: 0.5499761473501643 and parameters: {'max_depth': 14, 'learning_rate': 0.2508318583546198, 'n_estimators': 459, 'subsample': 0.6026043079642784, 'colsample_bytree': 0.8343968911571079, 'gamma': 0.5989632045923419}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:52,033] Trial 27 finished with value: 0.480534505489471 and parameters: {'max_depth': 13, 'learning_rate': 0.2689749064175391, 'n_estimators': 394, 'subsample': 0.6639403356424872, 'colsample_bytree': 0.9644185163970153, 'gamma': 4.212503579426876}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:54,890] Trial 28 finished with value: 0.5290913702397569 and parameters: {'max_depth': 9, 'learning_rate': 0.22879979083275115, 'n_estimators': 354, 'subsample': 0.6411574245494005, 'colsample_bytree': 0.766004769387504, 'gamma': 1.5631078214552399}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:35:57,487] Trial 29 finished with value: 0.5067833956153962 and parameters: {'max_depth': 17, 'learning_rate': 0.2006098859235838, 'n_estimators': 301, 'subsample': 0.7356643883566745, 'colsample_bytree': 0.9437604515662346, 'gamma': 1.6522680636499794}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:01,780] Trial 30 finished with value: 0.5442190094662008 and parameters: {'max_depth': 15, 'learning_rate': 0.1476288622858343, 'n_estimators': 478, 'subsample': 0.7059176008448868, 'colsample_bytree': 0.9094655785926786, 'gamma': 0.650109448561884}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:05,943] Trial 31 finished with value: 0.5444345791362608 and parameters: {'max_depth': 13, 'learning_rate': 0.24326889289215267, 'n_estimators': 453, 'subsample': 0.6061694642671313, 'colsample_bytree': 0.8323575275327422, 'gamma': 0.17184670326359922}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:09,379] Trial 32 finished with value: 0.5515226517378593 and parameters: {'max_depth': 14, 'learning_rate': 0.28113212890396505, 'n_estimators': 459, 'subsample': 0.6244112165175847, 'colsample_bytree': 0.8510359885369141, 'gamma': 0.7352661177768279}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:12,205] Trial 33 finished with value: 0.5224821796898331 and parameters: {'max_depth': 15, 'learning_rate': 0.28691827477542475, 'n_estimators': 415, 'subsample': 0.6868419119714438, 'colsample_bytree': 0.8628470059340317, 'gamma': 2.3886538003425533}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:15,233] Trial 34 finished with value: 0.5420500077852514 and parameters: {'max_depth': 12, 'learning_rate': 0.27026388577514604, 'n_estimators': 379, 'subsample': 0.6267144144343313, 'colsample_bytree': 0.9561875214756055, 'gamma': 1.2096939455680458}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:19,310] Trial 35 finished with value: 0.5284426991050699 and parameters: {'max_depth': 10, 'learning_rate': 0.21740644292029732, 'n_estimators': 493, 'subsample': 0.656836664739215, 'colsample_bytree': 0.8895192956572406, 'gamma': 0.4702751561211377}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:22,395] Trial 36 finished with value: 0.5424221030263855 and parameters: {'max_depth': 18, 'learning_rate': 0.26084607630913437, 'n_estimators': 436, 'subsample': 0.7709623370426604, 'colsample_bytree': 0.8078363835712857, 'gamma': 1.404318150533892}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:25,262] Trial 37 finished with value: 0.4847068242170144 and parameters: {'max_depth': 15, 'learning_rate': 0.12019049539270835, 'n_estimators': 325, 'subsample': 0.6849031291338668, 'colsample_bytree': 0.9264962724887317, 'gamma': 2.5309397215716873}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:27,935] Trial 38 finished with value: 0.4348626897612592 and parameters: {'max_depth': 13, 'learning_rate': 0.2843905235283904, 'n_estimators': 467, 'subsample': 0.6287207056842704, 'colsample_bytree': 0.7648529242094675, 'gamma': 7.456115950090389}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:29,203] Trial 39 finished with value: 0.45997582708441803 and parameters: {'max_depth': 20, 'learning_rate': 0.16940799304274862, 'n_estimators': 88, 'subsample': 0.6515403098210402, 'colsample_bytree': 0.8541144081872352, 'gamma': 4.564120494991744}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:35,147] Trial 40 finished with value: 0.49616942462119795 and parameters: {'max_depth': 14, 'learning_rate': 0.025612360889220087, 'n_estimators': 405, 'subsample': 0.7217764160394774, 'colsample_bytree': 0.9751664827253662, 'gamma': 2.028757354781931}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:38,732] Trial 41 finished with value: 0.5347747848465015 and parameters: {'max_depth': 14, 'learning_rate': 0.24228231087584984, 'n_estimators': 461, 'subsample': 0.6122639402661387, 'colsample_bytree': 0.8444866036669623, 'gamma': 0.6927016071641048}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:42,624] Trial 42 finished with value: 0.5486448123272197 and parameters: {'max_depth': 16, 'learning_rate': 0.2540626121438394, 'n_estimators': 433, 'subsample': 0.6003219257856705, 'colsample_bytree': 0.8830268044444592, 'gamma': 0.47314695761219877}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:45,881] Trial 43 finished with value: 0.5318306210829004 and parameters: {'max_depth': 14, 'learning_rate': 0.23937056042110513, 'n_estimators': 362, 'subsample': 0.6334003590438565, 'colsample_bytree': 0.8129621643052312, 'gamma': 0.9905527424468935}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:49,639] Trial 44 finished with value: 0.5446399650128508 and parameters: {'max_depth': 11, 'learning_rate': 0.28820315568959287, 'n_estimators': 448, 'subsample': 0.6215432550916853, 'colsample_bytree': 0.8298765271905449, 'gamma': 0.4917078658694334}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:53,371] Trial 45 finished with value: 0.5455257300801306 and parameters: {'max_depth': 13, 'learning_rate': 0.21109231062684308, 'n_estimators': 497, 'subsample': 0.6508921690502432, 'colsample_bytree': 0.7936559448007823, 'gamma': 1.3178249468894305}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:56,724] Trial 46 finished with value: 0.546058969164495 and parameters: {'max_depth': 10, 'learning_rate': 0.1903368143787718, 'n_estimators': 387, 'subsample': 0.7573163151472373, 'colsample_bytree': 0.7092424477036008, 'gamma': 0.8397033288830882}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:36:59,005] Trial 47 finished with value: 0.42226308435351767 and parameters: {'max_depth': 12, 'learning_rate': 0.2533230976259209, 'n_estimators': 346, 'subsample': 0.6924987809505284, 'colsample_bytree': 0.8734936587652046, 'gamma': 8.287640935191234}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:37:01,808] Trial 48 finished with value: 0.4357979352376115 and parameters: {'max_depth': 16, 'learning_rate': 0.22803126155330466, 'n_estimators': 424, 'subsample': 0.8697968227718615, 'colsample_bytree': 0.9041944777584237, 'gamma': 6.469689611673805}. Best is trial 11 with value: 0.5564602130144541.
[I 2025-04-28 13:37:05,426] Trial 49 finished with value: 0.5605274947832962 and parameters: {'max_depth': 18, 'learning_rate': 0.29755962838250477, 'n_estimators': 300, 'subsample': 0.7999204458557698, 'colsample_bytree': 0.6152150206299387, 'gamma': 0.04288615684966515}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:07,377] Trial 50 finished with value: 0.3843373403743663 and parameters: {'max_depth': 18, 'learning_rate': 0.29900819078251056, 'n_estimators': 291, 'subsample': 0.8027231384516685, 'colsample_bytree': 0.7129695109809626, 'gamma': 9.893396704839645}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:11,119] Trial 51 finished with value: 0.5380807703093305 and parameters: {'max_depth': 7, 'learning_rate': 0.27434494466610526, 'n_estimators': 312, 'subsample': 0.9209054272086425, 'colsample_bytree': 0.6537337689081537, 'gamma': 0.018873904156447276}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:13,792] Trial 52 finished with value: 0.5451007474390825 and parameters: {'max_depth': 19, 'learning_rate': 0.2633121182531507, 'n_estimators': 279, 'subsample': 0.6154593050267996, 'colsample_bytree': 0.6126156101760198, 'gamma': 0.4037092768615871}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:16,461] Trial 53 finished with value: 0.5245760249499126 and parameters: {'max_depth': 14, 'learning_rate': 0.29181154327317266, 'n_estimators': 332, 'subsample': 0.8149163683648439, 'colsample_bytree': 0.8343278588170129, 'gamma': 1.004852258590314}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:18,604] Trial 54 finished with value: 0.5040630584742353 and parameters: {'max_depth': 15, 'learning_rate': 0.273442917629668, 'n_estimators': 253, 'subsample': 0.8517112547943483, 'colsample_bytree': 0.8887550207252429, 'gamma': 1.9155149881861275}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:21,967] Trial 55 finished with value: 0.536311449541149 and parameters: {'max_depth': 18, 'learning_rate': 0.2805769997165783, 'n_estimators': 475, 'subsample': 0.785152744062777, 'colsample_bytree': 0.6002338182201412, 'gamma': 0.3398686774627526}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:25,516] Trial 56 finished with value: 0.5156659386143174 and parameters: {'max_depth': 11, 'learning_rate': 0.1007268531256979, 'n_estimators': 370, 'subsample': 0.9772210307430288, 'colsample_bytree': 0.8608911051817689, 'gamma': 0.7816815311271937}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:28,317] Trial 57 finished with value: 0.541172963762253 and parameters: {'max_depth': 20, 'learning_rate': 0.2456644728445471, 'n_estimators': 175, 'subsample': 0.6366646795924179, 'colsample_bytree': 0.7787931368085201, 'gamma': 0.015603066160549184}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:31,263] Trial 58 finished with value: 0.5113282357378015 and parameters: {'max_depth': 16, 'learning_rate': 0.2612898157555607, 'n_estimators': 399, 'subsample': 0.6751147161411085, 'colsample_bytree': 0.9235748593977251, 'gamma': 1.51619769866943}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:34,202] Trial 59 finished with value: 0.5127058695387423 and parameters: {'max_depth': 12, 'learning_rate': 0.2305590638725548, 'n_estimators': 341, 'subsample': 0.834990669713944, 'colsample_bytree': 0.9440638555826228, 'gamma': 1.0633361727558137}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:36,455] Trial 60 finished with value: 0.5029053891304969 and parameters: {'max_depth': 9, 'learning_rate': 0.297899777484677, 'n_estimators': 319, 'subsample': 0.7611966309863104, 'colsample_bytree': 0.8411766460325516, 'gamma': 3.0121679274123134}. Best is trial 49 with value: 0.5605274947832962.
[I 2025-04-28 13:37:39,979] Trial 61 finished with value: 0.5343460501133126 and parameters: {'max_depth': 16, 'learning_rate': 0.25331566789221244, 'n_estimators': 433, 'subsample': 0.6038191549532526, 'colsample_bytree': 0.8794138249698652, 'gamma': 0.5918042524278849}. Best is trial 49 with value: 0.5605274947832962.

Best params: {'max_depth': 11, 'learning_rate': 0.1630961562110346, 'n_estimators': 332, 'subsample': 0.6659706776375881, 'colsample_bytree': 0.773801675255497, 'gamma': 0.0404296614070354}

In [18]:
params = study.best_trial.params
params

{'max_depth': 11,
 'learning_rate': 0.1630961562110346,
 'n_estimators': 332,
 'subsample': 0.6659706776375881,
 'colsample_bytree': 0.773801675255497,
 'gamma': 0.0404296614070354}

In [19]:
# train with the best params
best_model = xgb.XGBClassifier(**params)
best_multi_model = MultiOutputClassifier(best_model)
best_multi_model.fit(X_train, y_train)

MultiOutputClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample_bytree=0.773801675255497,
                                              device=None,
                                              early_stopping_rounds=None,
                                              enable_categorical=False,
                                              eval_metric=None,
                                              feature_types=None,
                                              gamma=0.0404296614070354,
                                              grow_policy=None,
                                              importance_type=None,
                                              interaction_constraints=None,
                                              learning_rate=0.1630961562110346,
                                              max_bin=None,
                                              max_cat_threshold=None,
                                              max_cat_to_onehot=None,
                                              max_delta_step=None, max_depth=11,
                                              max_leaves=None,
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=332, n_jobs=None,
                                              num_parallel_tree=None,
                                              random_state=None, ...))

In [20]:
participant_id = X_val['participant_id']
X_val = X_val.drop(columns = 'participant_id')

In [21]:
# score test set
y_pred = best_multi_model.predict(X_val)

In [22]:
predictions_df = pd.DataFrame(
    y_pred,
    columns=['Predicted_ADHD', 'Predicted_Gender']
)

# Combine participant IDs with predictions
result_df = pd.concat([participant_id.reset_index(drop=True), predictions_df], axis=1)

# Print or save the DataFrame
print(result_df)

    participant_id  Predicted_ADHD  Predicted_Gender
0     ExV0vwCIzAWp               1                 0
1     oSlcxZbncT7a               0                 1
2     28mwHUApaS7q               1                 0
3     8E7WIqYsBQBj               1                 0
4     Hn7obzzz4omm               1                 0
..             ...             ...               ...
359   0FUWCjn9YMN1               1                 0
360   d3VfkRYzJJXX               1                 0
361   vRp3pYC1P44F               1                 0
362   ePfFpufOYJFy               0                 0
363   Jz96BoYNDD51               1                 0

[364 rows x 3 columns]

In [23]:
y_val = y_val.drop(columns = 'participant_id')

In [24]:
f1_test = weighted_f1(y_val, predictions_df)
print(f"Weighted F1 score on test set: {f1_test}")

Weighted F1 score on test set: 0.605574812247256

In [25]:
def multi_output_accuracy(y_true, y_pred):
    # Ensure y_true and y_pred are NumPy arrays
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)
    # Compute accuracy for each target variable and return the mean
    return np.mean([accuracy_score(y_true[:, i], y_pred[:, i]) for i in range(y_true.shape[1])])

In [26]:
accuracy_test = multi_output_accuracy(y_val, predictions_df)
print(f"Multi-output accuracy on test set: {accuracy_test}")

Multi-output accuracy on test set: 0.6469780219780219

## Train on whole dataset and score test set

In [ ]:
X_scaled = X_scaled.drop(columns=['participant_id'], axis=1)
y = y.drop(columns=['participant_id'], axis=1)

In [31]:
# train with the best params
final_model = xgb.XGBClassifier(**params)
final_multi_model = MultiOutputClassifier(final_model)
final_multi_model.fit(X_scaled, y)

MultiOutputClassifier(estimator=XGBClassifier(base_score=None, booster=None,
                                              callbacks=None,
                                              colsample_bylevel=None,
                                              colsample_bynode=None,
                                              colsample_bytree=0.773801675255497,
                                              device=None,
                                              early_stopping_rounds=None,
                                              enable_categorical=False,
                                              eval_metric=None,
                                              feature_types=None,
                                              gamma=0.0404296614070354,
                                              grow_policy=None,
                                              importance_type=None,
                                              interaction_constraints=None,
                                              learning_rate=0.1630961562110346,
                                              max_bin=None,
                                              max_cat_threshold=None,
                                              max_cat_to_onehot=None,
                                              max_delta_step=None, max_depth=11,
                                              max_leaves=None,
                                              min_child_weight=None,
                                              missing=nan,
                                              monotone_constraints=None,
                                              multi_strategy=None,
                                              n_estimators=332, n_jobs=None,
                                              num_parallel_tree=None,
                                              random_state=None, ...))

In [32]:
# score test data
y_test_pred = final_multi_model.predict(X_test_scaled)
predictions_test_df = pd.DataFrame(
    y_test_pred,
    columns=['ADHD_Outcome', 'Sex_F']
)
# Combine participant IDs with predictions
result_test_df = pd.concat([test_participant_id.reset_index(drop=True), predictions_test_df], axis=1)

result_test_df

    participant_id  ADHD_Outcome  Sex_F
0     Cfwaf5FX7jWK             1      0
1     vhGrzmvA3Hjq             1      1
2     ULliyEXjy4OV             1      0
3     LZfeAb1xMtql             1      0
4     EnFOUv0YK1RG             0      0
..             ...           ...    ...
299   UadZfjdEg7eG             1      0
300   IUEHiLmQAqCi             1      1
301   cRySmCadYFRO             1      0
302   E3MvDUtJadc5             1      0
303   dQJXfyRazknD             1      0

[304 rows x 3 columns]

In [33]:
result_test_df.to_csv(os.path.join(data_dir, 'output/huizi_xgboost_balance.csv'), index=False)